export default Object.freeze({
  INSTALL_EXTERNAL_DEPENDENCY: "INSTALL_EXTERNAL_DEPENDENCY",
  COPY_COMPONENT_CODE: "COPY_COMPONENT_CODE",
  COPY_COMPONENT_STYLES: "COPY_COMPONENT_STYLES",
  COMPONENT_USAGE: "COMPONENT_USAGE"
});
